(* ::Package:: *)

(************************************************************************)
(* This file was generated automatically by the Mathematica front end.  *)
(* It contains Initialization cells from a Notebook file, which         *)
(* typically will have the same name as this file except ending in      *)
(* ".nb" instead of ".m".                                               *)
(*                                                                      *)
(* This file is intended to be loaded into the Mathematica kernel using *)
(* the package loading commands Get or Needs.  Doing so is equivalent   *)
(* to using the Evaluate Initialization Cells menu command in the front *)
(* end.                                                                 *)
(*                                                                      *)
(* DO NOT EDIT THIS FILE.  This entire file is regenerated              *)
(* automatically each time the parent Notebook file is saved in the     *)
(* Mathematica front end.  Any changes you make to this file will be    *)
(* overwritten.                                                         *)
(************************************************************************)



(* :Title: Methods *)
(* :Context: MathObject`Methods` *)
(* :Summary: Subcontext definition *)
(* :Author: Mark A. Caprio, Department of Physics, University of Notre Dame *)
(* :Copyright: Copyright 2011, Mark A. Caprio *)
(* :Package Version: 1.0 *)
(* :Mathematica Version: 8.0 *)
(* :History: See main package file. *)


BeginPackage["MathObject`Methods`"];
Constructor::usage="Constructor[class,self][args] is the hook function for user constructor actions in MathObject package objects.";
OnCreationFailure::usage="OnCreationFailure[class,self][args] is the hook function invoked when the constructor call is not matched when creating an instance of a MathObject package object.  Definition of such a function is optional.";
Destructor::usage="Destructor[class,self][] is the hook function for user destructor actions in MathObject package objects.  Definition of such a function is optional.";
EndPackage[];
